# Generated by Django 5.2.7 on 2025-10-09 17:08

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Caterogie')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=100, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=200, populate_from='title', unique=True)),
                ('status', models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISHED')], default='0', max_length=1, verbose_name='Statut')),
                ('section', models.CharField(choices=[('Recent', 'Recent Posts'), ('Popular', 'Popular Posts'), ('Trending', 'Trending Posts'), ('Inspiration', 'Inspiration Posts'), ('Lifestyle', 'Lifestyle Posts')], default='Recent', max_length=100, verbose_name='Section')),
                ('main_post', models.BooleanField(default=False, verbose_name='Post Principal')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='Home.category', verbose_name='Catégorie')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
